version: "3"
services:
  django:
    container_name: django
    build: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"