version: "3"
services:
  django:
    container_name: django
    build: .
    command: >
        sh -c "python manage.py collectstatic --noinput && 
        gunicorn --bind 0.0.0.0:8000 stateArt.wsgi:application"
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"