version: "3"
services:
  django:
    container_name: django
    build: .
    command: >
      sh -c "&& gunicorn stateArt.wsgi:application --bind 0.0.0.0:8000"
#      "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py createsuperuser --noinput"
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - django
volumes:
  static:
  media:
  pgdata:
