# Generated by Django 4.2.6 on 2023-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(verbose_name='Текст новости')),
                ('img', models.ImageField(upload_to='static/upload_img/', verbose_name='img в новости')),
            ],
            options={
                'verbose_name': 'Новости на главной странице',
                'verbose_name_plural': 'Новости на главной странице',
            },
        ),
    ]
