# Generated by Django 4.2.6 on 2023-11-16 20:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar_counters_and_reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Барные стойки и ресепшен',
                'verbose_name_plural': 'Барные стойки и ресепшен',
            },
        ),
        migrations.CreateModel(
            name='Benches_and_gazebos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Скамейки и беседки',
                'verbose_name_plural': 'Скамейки и беседки',
            },
        ),
        migrations.CreateModel(
            name='Colums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Колонны',
                'verbose_name_plural': 'Колонны',
            },
        ),
        migrations.CreateModel(
            name='Decorative_fasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Декоративный крепеж',
                'verbose_name_plural': 'Декоративный крепеж',
            },
        ),
        migrations.CreateModel(
            name='Entrances_and_doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Вход и двери',
                'verbose_name_plural': 'Вход и двери',
            },
        ),
        migrations.CreateModel(
            name='Furniture_and_interior_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Мебель и элементы интерьера',
                'verbose_name_plural': 'Мебель и элементы интерьера',
            },
        ),
        migrations.CreateModel(
            name='Non_standard_metal_structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Нестандартные металлоконструкции',
                'verbose_name_plural': 'Нестандартные металлоконструкции',
            },
        ),
        migrations.CreateModel(
            name='Our_workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Наш цех',
                'verbose_name_plural': 'Наш цех',
            },
        ),
        migrations.CreateModel(
            name='Perforated_sheet_metal_structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Конструкции из перфолиста',
                'verbose_name_plural': 'Конструкции из перфолиста',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': '"Бассейн" частный проект. Описание производства и монтажа',
                'verbose_name_plural': '"Бассейн" частный проект. Описание производства и монтажа',
            },
        ),
        migrations.CreateModel(
            name='Production_and_metalworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Производство и металлообработка',
                'verbose_name_plural': 'Производство и металлообработка',
            },
        ),
        migrations.CreateModel(
            name='Trusses_and_frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Фермы и каркасы',
                'verbose_name_plural': 'Фермы и каркасы',
            },
        ),
        migrations.CreateModel(
            name='Сanopies_and_canopies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('canonical', models.CharField(blank=True, max_length=255, null=True, verbose_name='canonical')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title_h1_1', models.CharField(max_length=250, verbose_name='Заголовок (h1)')),
                ('img_article', models.ImageField(upload_to='static/upload_img/', verbose_name='img')),
                ('description_1', tinymce.models.HTMLField(verbose_name='Описание (блок 1)')),
                ('title_h1_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй заголовок (h2) на странице для второго блока')),
                ('description_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 2 напротив img)')),
                ('description_3', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (блок 3 под img) ')),
            ],
            options={
                'verbose_name': 'Навесы и козырьки',
                'verbose_name_plural': 'Навесы и козырьки',
            },
        ),
    ]
